name: Generate Changelog
on:
  push:
    branches: [ main ]
  release:
    types: [published]
permissions:
  contents: write
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install git-cliff
        uses: orhun/git-cliff-action@v3
        with:
          config: .gitcliff.toml
          args: -v --tag-pattern 'v*' -o CHANGELOG.md
      - name: Commit CHANGELOG.md
        run: |
          if [ -n "$(git status --porcelain CHANGELOG.md)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "docs(changelog): update"
            git push
          fi
